### ISSUE TITLE
Performance/Bug: if you go into apartment, move around and go outside

### ISSUE THREAD

**Issue by r4pt0s** [zero-to-mastery/ZTM-Quest#104]
There is currently a performance issue if you go into the campus_house_1, move around there and outside again. It might not happen at first, but if you do it again you will encounter bad performance while trying to move around.

This issue should fix the performance problem but not that you come out of the arcade.

The reason for it might be how NPCs get spawned in the city map.

**Comment by UnmuktShukla** [comment]
Hello! I am looking forward to contribute to this project. I am new to open source and would really appreciate if you could guide me a bit about what needs to be done here

**Comment by r4pt0s** [comment]
Hi @UnmuktShukla,

I'm currently on it. We can discuss how you can help out though. You can tag me in our ZTM Discord server in the hacktoberfest channel 🙌🏻
