### ISSUE TITLE
Feature: Add fishing game to pond in map_forest_junction

### ISSUE THREAD

**Issue by r4pt0s** [zero-to-mastery/ZTM-Quest#119]
Because we got two new great maps, we need also more interactions for those.
The scope of this issue is, creating a fishing feature for the pond in map_forest_junction.

Once the player collides with the pond, a dialog box has to appear.
Content of the dialog box should be a short intro text about what will happen next.
The user can choose between two versions of the interaction. 

## 1. Level Beginner
If the user chooses this level, then a simple animation should happen where you can see the main character throwing a fishing line into the pond, the line is moving slowly towards the main character and has to look like as it would move up and down the water. 
At one point close to the main character, the line should pull down and a notice has to appear which keyboard key the user as to press. Keep in mind that we don't have a keyboard on mobile devices. 
After hitting the key or taping the screen, the fishing line should get out of the water with a fish on it. 
At the current stage, the user should get a congratulations notice and a internal player state `catchedFishes` count should get increased by one for future features. 

## 2. Level Pro
If the user chooses this level, a new minigame in a new scene should pop up. 
This new scene should contain a fully fledged fishing mini game. 
There are a bunch of possible ways to realize this mini game. You can use a existing idea from one of the AAA games which you might have played in the past or come up with your entirely new idea. 

---
Remember to add new asset credits to asset_credits.md if you add them to the game.

**Comment by fullspeccoder** [comment]
Will do it if Assigned!

**Comment by r4pt0s** [comment]
Done @fullspeccoder.
Go for it 🎉🚀
