### ISSUE TITLE
Adding moving cars to map_city 

### ISSUE THREAD

**Issue by r4pt0s** [zero-to-mastery/ZTM-Quest#120]
The streets are currently empty in map_city.
This issue should add moving cars to the streets.
They should get spawned on one of the street edges, drive the entire street along and should disappear once they reach the boundaries of the map.
You can use one of these spritesheets which I already found

https://tokka.itch.io/top-down-car
https://www.kenney.nl/assets/pixel-vehicle-pack
https://minzinn.itch.io/pixelvehicles

Regardless of if you are using one of the mentioned spritesheets of not, please don't forget to add them to asset_credits.md to give a shoutout to the creators.

**Comment by leonyangela** [comment]
Hi, can I work on this? Thanks

**Comment by r4pt0s** [comment]
Absolutely @leonyangela.
Go for it 🎉🚀

**Comment by gdsouza1992** [comment]
@leonyangela, I tried to research doing this last week but gave up due to not having enough time, but some good starting points are exploring the Navmesh / patrol functions that kaplay gives ootb.
