### ISSUE TITLE
Feature: Add inventory interface for main character

### ISSUE THREAD

**Issue by r4pt0s** [zero-to-mastery/ZTM-Quest#122]
Every good game has some kind of inventory for the main character so should we have one.

Add a inventory interface where the user can see what items got collected along the ride.
In the near future we will implement also a way to use items to proceed or to solve mysteries.

The interface should get added on top of the game canvas.
Due to performance reasons, I would recommend to add it via HTML and css like we did with the dialog boxes.
Because we can communicate also from outside the game canvas with the kaplay context, it should totally be a valid option.

It would also be easier to design or replace the inventory interface because of the architecture.

This makes this issue also doable for beginners which might want to join our journey creating a game from scratch.

**Comment by UnmuktShukla** [comment]
Hello! I would like to work on this

**Comment by r4pt0s** [comment]
Cool @UnmuktShukla.
Go for it 🎉🚀

**Comment by UnmuktShukla** [comment]
Hey! I have completed this task and have added an PR. Please have a look.
Thankyou 👍🏼

**Comment by r4pt0s** [comment]
@UnmuktShukla yep, saw it already and answered in the PR🙌🏻
