### ISSUE TITLE
Bug 🐞: Dino Game on Machine 6

### ISSUE THREAD

**Issue by fullspeccoder** [zero-to-mastery/ZTM-Quest#126]
If the user has a large screen, the user can't play it correctly. It appears the platform is too small to work and so the game will run on forever.

![Screenshot 2024-10-09 at 8 29 19 AM](https://github.com/user-attachments/assets/6a89fe63-3d33-4a64-9314-25e18fa9d842)

**Comment by r4pt0s** [comment]
@BrianCheung1 wanna look into it?

**Comment by BrianCheung1** [comment]
Yes will do when i get the chance, another bug connected to this due to the the new GBA frame, all the games will not work anymore due to them using height of the screen to determine their platforms/objects.
