### ISSUE TITLE
Bug: Unable to move after entering arcade

### ISSUE THREAD

**Issue by BrianCheung1** [zero-to-mastery/ZTM-Quest#167]
## Expected Behavior
Player should still be able to move freely

## Current Behavior
Player is unable to move around with mouse clicks or WASD/Arrow keys even when refreshing page or starting a new game

## Possible Solution
N/A

## Steps to Reproduce
1. Fresh Start at the academy
2. Use Toilet and wash hand
3. Talk to bruce and exit academy
4. Mute sounds and walk into arcade
5. Unable to move character after entering arcade

## Browser/OS
Tested Version 129.0.6668.101 (Official Build) (64-bit) Chrome/ Windows 10
Tested IOS 16/Safari

**Comment by r4pt0s** [comment]
The same problem occurs if you go to one of the snack bars or stalls.
Also, by going back into the academy.

This is related to the last rewrite and the isInDialog state from localstorage.

@fullspeccoder : do you want to look into it?

**Comment by fullspeccoder** [comment]
@r4pt0s Yes, I just fixed it! Very simple 😅
