### ISSUE TITLE
Polish ui for dialogues

### ISSUE THREAD

**Issue by r4pt0s** [zero-to-mastery/ZTM-Quest#20]
The current dialogue UI style is pretty simple. 
Although it looks okay-ish there is room for improvement.

For example, there is no name tag on the dialogue about who is actually talking currently.
The dialogue box is written in html and css filled with javascript.

You can (and you should) stick to vanilla html and css to design and style the dialogue box.

You can find the current setup in [index.html](https://github.com/zero-to-mastery/ZTM-Quest/blob/main/index.html). It would be also nice to seperate the css from the html file.

**Comment by aadityaforwork** [comment]
![image](https://github.com/user-attachments/assets/e4d9f89f-9652-41ac-96dd-1726bfa11a10)



Hello I have added updated the dialogue box with it's UI as well as the character name is dynamically getting updated does  this look good to proceed with or any further changes are there to be done?

**Comment by r4pt0s** [comment]
@aadityaforwork a good starting point. I thought more of something like [this](https://images.app.goo.gl/9p2NJscsiGfxENkA6)

Where the name tag is a bit floating above the content box

What do you think?

**Comment by aadityaforwork** [comment]
> @aadityaforwork a good starting point. I thought more of something like [this](https://images.app.goo.gl/9p2NJscsiGfxENkA6)
> 
> Where the name tag is a bit floating above the content box
> 
> What do you think?

I was thinking  that in an instance where two or more people are involved in the conversation then updating it inside the content would be much more simplistic and better-looking , but sure we can try it placing above the content box as well I am sure it would add some uniqueness!

**Comment by r4pt0s** [comment]
Would be great @aadityaforwork .
You already prepared it by passing in the name as I saw.

**Comment by r4pt0s** [comment]
@aadityaforwork just let me know when your PR is ready.

**Comment by aadityaforwork** [comment]
> Would be great @aadityaforwork . You already prepared it by passing in the name as I saw.

I tried this the problem is that it looks clean inside a single container whereas when we put the character name in a floating box above the content box it seems messy also does not align with the background!
My opinion is that let us keep it in a single container at least for now would love to hear your opinion about it.

**Comment by r4pt0s** [comment]
@aadityaforwork it is okay for me as long as the name is configurable and clearly visible that it is the name and not the conversation text 🙌🏻

**Comment by aadityaforwork** [comment]
> @aadityaforwork it is okay for me as long as the name is configurable and clearly visible that it is the name and not the conversation text 🙌🏻

then I feel the current UI looks configurable and good to go , also PR is ready too.
