### ISSUE TITLE
Add a game over scene with credits for assets and code contributions

### ISSUE THREAD

**Issue by r4pt0s** [zero-to-mastery/ZTM-Quest#21]
Each game usually has a game over scene.
Due to the fact, that losing in this game is not possible, we need a game over scene which can get triggered anytime by the user so to speak.
The time when the game over scene starts doesn't really matter for this scope.

It should just be callable anytime.

The content of the game over scene should contain credits for the assets we use (which you can find [here](https://github.com/zero-to-mastery/ZTM-Quest/blob/main/asset_credits.md) ) and nice to have, the name of the contributors of this game which you can fetch via github api.

Like a real game end scene which we know from AAA titles

**Comment by Kannav02** [comment]
Hey @r4pt0s 

Just to clarify some points before moving ahead

- create a gameOver() function
- create a button that triggers this function at any time by the user.
- the UI should contain the assets and the name of the contributors fetched via github API?
- Is there a specific style you'd like for the credits page? Additionally, what are your preferences for the technology or tools to be used in styling it?

if these are all the requirements, I would love to work on this issue , thank you!

**Comment by r4pt0s** [comment]
Hi @Kannav02,

Find the explanations below:

> create a gameOver() function

Exactly, or better said, a gameOver scene. Head over to [scenes](https://github.com/zero-to-mastery/ZTM-Quest/tree/main/src/scenes) to get an idea how.

> create a button that triggers this function at any time by the user.

I let it up to you how exactly it should get triggered. If it is a button, then make sure it is not overlapping another area which might be of interest.

> the UI should contain the assets and the name of the contributors fetched via github API?

Exactly. You can fetch the asset credits from [here](https://github.com/zero-to-mastery/ZTM-Quest/blob/main/asset_credits.md). I found a helpful articel which explains how you can load the file content via the github api which you can find [here](https://hackernoon.com/how-to-fetch-large-data-files-through-github-api)
Also, the contributors are fetchable via the github api. To make things easier, I figured already the url out which is
`https://api.github.com/repos/zero-to-mastery/ZTM-Quest/contributors`

> Is there a specific style you'd like for the credits page? Additionally, what are your preferences for the technology or tools to be used in styling it?

No, no specific style thought of right now. The only requirement is, that it should be compatible with the overall game design that it does not look like a entire new thing :sweat_smile: 
There are no preferences regarding technology or tools. 
I only mentioned [Tiled](https://www.mapeditor.org/) for map design (which you might not need because the screen is not a map) and [CakeWalk](https://www.bandlab.com/products/cakewalk) for audio creation.
I personally use [GIMP](https://www.gimp.org/) to create graphics (like Bruno).

Just one important thing, if you use any third party assets, designs or styles, make sure to add them to the credits file so that we have a shout out to the creator and that those files are free to use under the right license.

Any further questions?
Should I assign it to you?

**Comment by Kannav02** [comment]
Perfect, this sounds like an exciting issue to work on 

I would love to work on this

thank you!

**Comment by r4pt0s** [comment]
Awesome @Kannav02.
Go for it 🚀🎉

**Comment by Kannav02** [comment]
Hey @r4pt0s !

sorry for the late response,
I was going through the entire codebase, this is my first time experimenting with `kaplay` library, it's vast.
I love how the project is structured and organized,

also, I wanted to add something that I found when I was playing around with the demo, 
in the `starting` area, I am not able to use `D` to move right, the browser that I ran this on was `Chrome`, and the Operating System is `Mac`

**Comment by r4pt0s** [comment]
Hi @Kannav02,

Thanks for the kind words about the project and the setup.

Thanks for reporting the key bindings issue. For now we will not add that information somewhere because in the UI on Desktop we show the arrow keys to use.

But maybe - as soon as the start menu scene is ready - I would add another issue where we can work on informing the user about the game controls in a info section like you have it in other games.
Letting the users choose the key bindings themselves would also be a option.

**Comment by Kannav02** [comment]
Hey @r4pt0s
in the PR #115 , 
I have now accomplished making a scene that displays the name of the contributors and also displays the asset credits, the code for which can be found in the `gameOver.js` file

the functionality would work as follows

- Press `o` on the keyboard to trigger the credits scene
- Press `x`, click on the `exit` button, or wait till the end of the credits to go back to the start scene

apart from this would you also want me to add a button, I thought that would clutter the screen given the dimensions of each scene, so I avoided it until I get some guidance for the same from you 


Last thing, for the credits scene, would you want a static background that would go with the credits scene that I have right now.

Thank you for your time

**Comment by r4pt0s** [comment]
Hi @Kannav02,

> apart from this would you also want me to add a button, I thought that would clutter the screen given the dimensions of each scene, so I avoided it until I get some guidance for the same from you

You are right. On desktop, you should find a please since we got a frame around the canvas now.
On mobile it is indeed a bit tricky to find a place.
Although at the very bottom.


> Last thing, for the credits scene, would you want a static background that would go with the credits scene that I have right now. 

It would be really cool if we would have same kind of static background at least. Maybe thd academy building from map city? 🤔🤔🤔

**Comment by Kannav02** [comment]
Sure I will look into all of these, also now given that the website also has a different layout from before, I would have to place the button so it's visually appealing carefully but doesn't distracts from the main feature of the game

**Comment by Kannav02** [comment]
Hey @r4pt0s 

So to sum up

- I have added a credits button, it is in the canvas where the energy is displayed to make it better for the user to interact with it
- I have made sure the dynamic resizing works for each component in gameOver scene
- I have added an overlay background for the credits to be displayed

The issues that I am facing
- for some reason, if I use the sprite, it does not get updated when the scene is first loaded, even when I am calling the function, I have tested this out and found nothing that could be useful for me to solve this. Also, I have made the overlay to have a semi-transparent configuration for the color part but still, the sprite is not visible for some reason.
- as for the credits scene, if it is triggered when I am on a mobile screen layout, the text doesn't appear, however, if I trigger the scene from a laptop screen and resize it to a mobile screen, it works, I am not able to figure this out

I am so sorry for dragging this feature. I am just trying my best to figure out how I can resolve these issues, it's my first time using Kaplay, so I was just going over through docs and some StackOverflow threads to see if I could get this resolved which delayed it.

**Comment by r4pt0s** [comment]
Hi @Kannav02 ,

No worries at all.
It is a harder task as it might have looked initially.

There are a few gotcha for sure but nothing which you are not able to solve.
Let me look at your current solution.

I'm sure that we can figure out the missing parts together 🙌🏻.

**Comment by Kannav02** [comment]
Hey @r4pt0s

Thank you so much for the encouraging words! You're right, it turned out to be trickier than I initially thought, but I'm learning a lot along the way. I appreciate you taking the time to look over my current solution.

I'm looking forward to figuring out the remaining parts together!
Thanks again for your support 🙌🏻.

**Comment by r4pt0s** [comment]
@Kannav02 did you meant to look it like so

Desktop:
![desktop](https://github.com/user-attachments/assets/c5446ac5-8321-43f7-96d6-04d2074ab3d8)

Mobile:
![mobile](https://github.com/user-attachments/assets/03754570-5e83-412d-8859-f40ad059bb97)

**Comment by r4pt0s** [comment]
Then all you have to change is the following:

in src/scenes/gameover.js:

```javascript

// replace line 31-38 with
const background = k.add([
        k.sprite("backgroundImage", { width: k.width(), height: k.height() }),
        k.pos(0, 0),
        k.opacity(0.2),
        k.scale(1),
        k.z(60),
        k.fixed()
    ]);
```

- remove opacity on line from k.color in overlay
- remove line 57

```javascript
// add this line before const text= .....
const center = k.vec2((k.canvas.width / 2), k.canvas.height / 2);
```

- replace k.pos(k.width() * 0.5, k.height() * 0.5), with k.pos(center), in const text component list

```javascript
// add into updateLayout function at the top
const center = k.vec2((k.canvas.width / 2), k.canvas.height / 2);

//...

// replace
// text.pos = k.vec2(k.width() * 0.5, k.height() * 0.5);
// with
text.pos = center;
```

```javascript
// replace this code block
const textHeight = text.height * camScale;
let scrollPosition = -textHeight;
const scrollSpeed = 40 * camScale;
const maxScroll = textHeight + k.height() * 1.1;

// with this code block
const startPositionAncor = k.canvas.height * 2.8;
let scrollPosition = -startPositionAncor;
const scrollSpeed = 40 * camScale;
const maxScroll = text.height / 2.8;
```

and last step replace the following in the k.onUpdate function

```javascript
//replace this 
text.pos.y = k.height() - scrollPosition / camScale;

// with
text.pos.y = k.canvas.height - scrollPosition / camScale;
```


Let me know if you need more info or if something is unclear.
It worked all the time, but because we work a lot with zoom and canvas scaling, it is a bit trickier to find the right properties

**Comment by Kannav02** [comment]
Hey @r4pt0s!

Yes i was looking for the above design , for some reason my overlay was completely shadowing the sprite, thank you so much for the assist with this

if you don't mind me asking, are there any particular resource that could help me understand how the components and sprite would work with the dynamic resizing,


once again thank you so much for the help 

I will rebase my local branch , make the changes, and hopefully then this should be good for a PR review

**Comment by r4pt0s** [comment]
Hi @Kannav02 ,

You are welcome 🙌🏻.

Then main problem was the k.z()
Somehow, the transparency was not working properly on the overlay. Could be because kaplay is still in beta or transparency is not really working like we think it does 

What made the trick was setting the opacity on the background sprite and increase the z index of it to be higher as the one of the overlay.

I figured it out by reading the [kaplayjs docs](https://kaplayjs.com/doc/kaplay/)

Unfortunately, there are not really much resources out their which show you such tricks.

**Comment by Kannav02** [comment]
Hey!

I made a core change to the logic, for some issue the code that you gave for the canvas and scrolling was not working with the new changes made to the main branch, so the credits were not even showing up on the screen.

However seeing this, I thought I could implement a simpler logic wherein, there is a specific time taken for the credits to go over the user's screen and once that time has passed it would simply return back to the `start` scene, and that worked

I think my PR #115 should be good for review now

Thank you @r4pt0s for your support with this issue, if it was not for you, I wouldn't have been able to figure out the overlay part
