### ISSUE TITLE
Add a frame like a GBA frame which will contain the game canvas

### ISSUE THREAD

**Issue by r4pt0s** [zero-to-mastery/ZTM-Quest#24]
The background of the game canvas is currently just purple-ish dark.
It would be nice if there is some mask of a console which wraps the game canvas.

Add it with html,css only, no framework.

**Comment by AaryanProthi** [comment]
Hi @r4pt0s, can you assign this issue to me, it'll be my first experience with open source. I'll do my best.

**Comment by Karine91** [comment]
@r4pt0s  what is a GBA frame, could you elaborate on how it should look like?)

**Comment by r4pt0s** [comment]
@Karine91 of course.

I thought about moving the canvas layer into a frame [like this] (https://images.app.goo.gl/VAsBmFjEBMJUzpBUA)

So that we don't see the dark purple background.

**Comment by Karine91** [comment]
@r4pt0s I will try that, please assign it to me

**Comment by r4pt0s** [comment]
Yeah, sure @Karine91 .
Go for it 🚀🎉
