### ISSUE TITLE
Create trigger for starting conversations with NPC instead of start to chat on collide

### ISSUE THREAD

**Issue by r4pt0s** [zero-to-mastery/ZTM-Quest#27]
In map_start, if you run into Bruno, the conversation is happening right away.
If you have bad luck, you will keep running into Bruno and trigger the same conversation from scratch again.

Add the functionality, that you can trigger conversations by hitting the **t** key on the keyboard instead of starting the conversation on collide with the object.
This should be reusable everywhere, where we want to add conversations.

nice to have: skip conversations once they started.

**Comment by b-hexsoul** [comment]
Not surprised this is already an issue 👍🏼  I came here looking for this.

@r4pt0s any particular reason hitting t should be used? What about a modal pops up next to the character saying something like "${characterName} want's to talk with you?" Otherwise I would be pressing t at every sprite character.

**Comment by r4pt0s** [comment]
@b-hexsoul exactly this what I have thought of. 
Starting the conversation by running into the NPC was just the initial set up left to fix for the community as a good first issue 😁.

What the game needs is a user input for triggering interactions like starting a conversation or entering a new map or interacting with object xyz.

A notice like you mentioned would be great. Another thing which I thought of would be to also add the keyboard key as hint for the user what to press right now. Like in the good old games on the good old consoles and handhelds where you saw a icon with the key character like A so that you know which key you have to press to start the interaction.

**Comment by b-hexsoul** [comment]
Awesome. Working on a sort of wrapper around the existing stuff. ```interactionHandler``` function and you can pass in a call back is the idea right now. Should have something tomorrow

**Comment by r4pt0s** [comment]
Great @b-hexsoul.
Excited about with what you come up with

**Comment by b-hexsoul** [comment]
#59

**Comment by r4pt0s** [comment]
the fix for mobile get worked on in #66
