### ISSUE TITLE
Add a open door to one house which should be the the main characters house in the city

### ISSUE THREAD

**Issue by r4pt0s** [zero-to-mastery/ZTM-Quest#31]
Our main character lives currently nowhere.

Pick one house in the map_city map which should be the house of the main character where it can go into.
Feel free to add a new map which you can design as you like for the main character.

For more information, have a look at #7 about creating a new map

**Comment by BrianCheung1** [comment]
Added with pull request [#96](https://github.com/zero-to-mastery/ZTM-Quest/pull/96)
