### ISSUE TITLE
Store main characters props state in local storage

### ISSUE THREAD

**Issue by r4pt0s** [zero-to-mastery/ZTM-Quest#33]
Current state is, every time you reload the page, the game starts from scratch.
The main character already has a few props which you can find [here](https://github.com/zero-to-mastery/ZTM-Quest/blob/988d5087c56d11011ceef37ab84853b2d47f11f6/src/scenes/start.js#L27)

The goal is, to store the current props into local storage so that it can get loaded on page refresh.
Keep in mind, that if the props of the player have changed, that the local storage should get updated as well.

**Comment by gdsouza1992** [comment]
Ill take this
