### ISSUE TITLE
Bug Fix: washing hands

### ISSUE THREAD

**Issue by r4pt0s** [zero-to-mastery/ZTM-Quest#37]
Currently there is a bug where it is possible to wash hands first and go to toilet afterwards which will grant access to next map in map_start.

That is not the right way, of course not.
Fix the bug so that the player has to wash hands after he used the toilet.

**Comment by AdithyaPadmashali** [comment]
Hi @r4pt0s. I've made a PR with the fix for the issue. Please check it out.
Also, this project looks beautiful 🌟

**Comment by r4pt0s** [comment]
Thank you @AdithyaPadmashali.
Just merged it.
It got already deployed 🚀
