### ISSUE TITLE
When reached mailbox and popup showed up player still able to move by keyboard

### ISSUE THREAD

**Issue by Karine91** [zero-to-mastery/ZTM-Quest#46]
https://github.com/user-attachments/assets/94cdf8bf-4f74-4161-8ff4-4556b96fa733

**Comment by abdulrahimsulthan** [comment]
Let me handle this one. Looks like player flag not working, conversation input type mismatch or any other issue with the util function. Let me go through the logics.

**Comment by KevinBatdorf** [comment]
This was fixed in https://github.com/zero-to-mastery/ZTM-Quest/pull/54
