### ISSUE TITLE
@lorenzomiro could you maybe add the interaction to map_city instead of map_start?

### ISSUE THREAD

**Issue by lorenzomiro** [zero-to-mastery/ZTM-Quest#48]
@lorenzomiro could you maybe add the interaction to map_city instead of map_start?
In map_city, we already have set up two potential buildings with enter map tags where one of them could be a store.
Hava a look at [additional map infos](https://github.com/zero-to-mastery/ZTM-Quest/blob/main/additional-map-info%2Fmap_city%2Fobjects_map_city_1.png) where you can see the tag name of the buildings which you can use in your onCollide method.

_Originally posted by @r4pt0s in https://github.com/zero-to-mastery/ZTM-Quest/pull/44#pullrequestreview-2341186920_

**Comment by r4pt0s** [comment]
closed because it is part of the conversation of PR #44
