### ISSUE TITLE
Keyboard controls break after an interaction

### ISSUE THREAD

**Issue by MattCSmith** [zero-to-mastery/ZTM-Quest#49]
After closing an interaction you are unable to move the player with the keyboard. Once you have moved the player again with the mouse you can continue to use the keyboard. 

### How to replicate: 
1. Interact with the mailbox or Bruno
2. Close the dialogue
3. Try to use the arrow keys to move around

**Comment by KevinBatdorf** [comment]
This is actually a focus issue. When a dialog is opened it doesn't get focus, and when it finishes it doesn't give focus back to the game (clicking does, of course).

**Comment by r4pt0s** [comment]
@KevinBatdorf wanna fix it or do you want to leave it to someone else?

**Comment by bruno-keiko** [comment]
Hi there. I want to work on this issue.
