### ISSUE TITLE
Bug: Player props only work after page refresh

### ISSUE THREAD

**Issue by r4pt0s** [zero-to-mastery/ZTM-Quest#52]
If you open the game website the first time so that the local storage is not set yet, player props do not get stored properly.
Only after page refresh they are available.

Steps to reproduce:

- open a incognito tab or window
- go to https://zero-to-mastery.github.io/ZTM-Quest/
- go to the toilet
- wash your hands
- talk to bruno
- try to go out

What should happen:
You should be able to go outside

What actually happens:
If you try to go out, you will get the message saying you should talk to Bruno although you already did.
After refreshing the page, you are able to go outside right away

@gdsouza1992 wanna fix this one because you added the feature in #50?

**Comment by gdsouza1992** [comment]
Yeah i can take this

**Comment by gdsouza1992** [comment]
i think the issue is with how we are setting the state values, we only set them on dialog completion

> player.onCollide('restroom_sink', () => {
        player.isInDialog = true;
        displayDialogueWithoutCharacter(
            ['You washed your hands. Good job!'],
            () => {
                player.state.hasHandsWashed = true;
                player.isInDialog = false;
            }
        );
    });
    
    
 can you reproduce the issue if you click next on the dialogs until they close?

**Comment by gdsouza1992** [comment]
ill upload a video showing this behavior when i get some time

**Comment by r4pt0s** [comment]
> i think the issue is with how we are setting the state values, we only set them on dialog completion
> 
> > player.onCollide('restroom_sink', () => {
> > player.isInDialog = true;
> > displayDialogueWithoutCharacter(
> > ['You washed your hands. Good job!'],
> > () => {
> > player.state.hasHandsWashed = true;
> > player.isInDialog = false;
> > }
> > );
> > });
> 
> can you reproduce the issue if you click next on the dialogs until they close?

Yep, does also happen if you click next because you can't close thd dialog before reaching the last part of the text?
Did you try to reproduce it like I mentioned?

**Comment by r4pt0s** [comment]
@gdsouza1992 yep, also if you hit next.
Only a page refresh makes it work.

Exactly, the next button is in some cases there although it shouldn't (see #55)

**Comment by KevinBatdorf** [comment]
I fixed this in https://github.com/zero-to-mastery/ZTM-Quest/pull/78. The proxy needed a getter

**Comment by gdsouza1992** [comment]
Thanks for looking into it. I kept going down the rabit hole of initializing the state rather than thinking the issue could be in the retrieval

**Comment by r4pt0s** [comment]
Good job guys 🔥💯

**Comment by r4pt0s** [comment]
fixed by #78
