### ISSUE TITLE
Bug: Dialog box Next button does not work, or is shown although it shouldn't

### ISSUE THREAD

**Issue by gdsouza1992** [zero-to-mastery/ZTM-Quest#55]
Some of the dialog boxes that have the "Next" button dont seem to work. Eg Mailbox, restroom, handwash.

**Comment by r4pt0s** [comment]
@gdsouza1992  Exactly. And the reason for it might be, that the text is passed as array although there is only one item in it. As soon as you just pass the text itself, not as array which contains it, the next button should disappear.

**Comment by n00nchi** [comment]
Can I pick this up?

**Comment by r4pt0s** [comment]
Sure @n00nchi
Go for it 🚀🎉

**Comment by KevinBatdorf** [comment]
I guess I fixed this by accident in #74
