### ISSUE TITLE
Bug: mobile trigger for conversations shows last conversation => unresponsive end

### ISSUE THREAD

**Issue by r4pt0s** [zero-to-mastery/ZTM-Quest#76]
Hi @b-hexsoul,
Just merged #75 which fixes #66
I tested it now and found the following bug:

Steps to reproduce:

- talk to the joke teller by clicking on t
- go to Bruno 
- click on the t

What should happen: 
The conversation with Bruno starts with brunos text

What actually happens:
Another joke from the joke teller and if you hit close, you can't move the main character anymore. 

Wanna look into it?

**Comment by r4pt0s** [comment]
@KevinBatdorf can you check the changes which your PR #74 introduced if they still work?

**Comment by r4pt0s** [comment]
After investing the bug I found out, that it is related to #74.
The last interaction which is mentioned in the steps to reproduce, talk to the joke teller.
Then, if you talk to Bruno you will get another interaction with the joke teller.
If you then hit close, the isInDialogue state doesn't get set properly to false. Therfore, movement is still disabled @KevinBatdorf

**Comment by KevinBatdorf** [comment]
I can't seem to reproduce it. Can you explain it again or maybe a video?

**Comment by b-hexsoul** [comment]
I have a fix for this soon
